[package]
publish = false
name = "reinhardt-openapi"
version.workspace = true
description = "OpenAPI 3.0 schema generation and documentation"
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
async-trait = { workspace = true }
reinhardt-core = { workspace = true, features = ["serializers", "http"] }
reinhardt-openapi-macros = { workspace = true }
reinhardt-urls = { workspace = true }
reinhardt-viewsets = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = "0.9.33"
thiserror = { workspace = true }
indexmap = { version = "2.0", features = ["serde"] }
http = "1.3.1"
chrono = { workspace = true }
uuid = { workspace = true }
utoipa = { version = "^5.4.0", features = ["uuid", "url"] }
utoipa-swagger-ui = { version = "^9.0.2", default-features = false, features = [
    "vendored",
] }
tera = { workspace = true }
hyper = { workspace = true }
once_cell = { workspace = true }
base64 = { workspace = true }
inventory = "0.3"
regex = { workspace = true }
reinhardt-pages = { workspace = true, optional = true }

[features]
default = []
serializers = ["reinhardt-core/serializers"]
pages = ["dep:reinhardt-pages"]
full = ["serializers", "pages"]

[dev-dependencies]
tokio = { workspace = true }
