[package]
name = "reinhardt-openapi"
version.workspace = true
description = "OpenAPI 3.0 schema generation and documentation"
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
reinhardt-apps = { workspace = true }
reinhardt-openapi-macros = { path = "../openapi-macros", version = "0.1.0-alpha.1" }
reinhardt-serializers = { path = "../serializers", version = "0.1.0-alpha.1", optional = true }
reinhardt-viewsets = { path = "../../../reinhardt-views/crates/viewsets", version = "0.1.0-alpha.1" }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = "0.9.33"
thiserror = { workspace = true }
indexmap = { version = "2.0", features = ["serde"] }
http = "1.3.1"
chrono = { workspace = true }
uuid = { workspace = true }
utoipa = "^5.4.0"
utoipa-swagger-ui = { version = "^9.0.2", default-features = false }
tera = { workspace = true }
hyper = { workspace = true }
once_cell = { workspace = true }

[features]
default = []
serializers = ["reinhardt-serializers"]

[dev-dependencies]
tokio = { workspace = true }
