[package]
name = "reinhardt-tasks"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
reinhardt-apps = { workspace = true }

async-trait = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
chrono = "0.4"
uuid = { workspace = true }
cron = "0.13"

[dev-dependencies]
tokio = { workspace = true }
