[package]
name = "reinhardt-di-core"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "FastAPI-style dependency injection system for Reinhardt"
repository.workspace = true

[dependencies]
thiserror = { workspace = true }
async-trait = { workspace = true }
reinhardt-apps = { path = "../../../apps", version = "0.1.0-alpha.1" }
reinhardt-params = { path = "../params", version = "0.1.0-alpha.1" }

[dev-dependencies]
tokio-test = { workspace = true }
