[package]
publish = false
name = "reinhardt-pool"
version.workspace = true
description = "Generic database connection pool interface"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
reinhardt-core = { workspace = true }
sqlx = { workspace = true, features = [
  "runtime-tokio",
  "chrono",
  "postgres",
  "mysql",
  "sqlite",
] }
tokio = { version = "1.41", features = ["full"] }
async-trait = "0.1"
thiserror = "2.0"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.0", features = ["v4", "serde"] }

[dev-dependencies]
reinhardt-test = { workspace = true, features = ["testcontainers"] }
rstest = { workspace = true }
serde_json = "1.0"
testcontainers = { workspace = true }
