[package]
name = "reinhardt-rest-core"
version.workspace = true
description = "Core REST API functionality and base classes for Reinhardt"
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
jwt = ["dep:reinhardt-auth", "reinhardt-auth/jwt"]

[dependencies]
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
reinhardt-urls = { workspace = true, features = ["routers"] }
reinhardt-core = { workspace = true, features = ["auth", "pagination"] }
reinhardt-auth = { path = "../../../reinhardt-contrib/crates/auth", version = "0.1.0-alpha.1", optional = true }
reinhardt-openapi = { path = "../openapi" }

[dev-dependencies]
reinhardt-rest = { workspace = true }
