[package]
name = "reinhardt-rest-core"
version.workspace = true
description = "Core REST API functionality and base classes for Reinhardt"
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
jwt = ["reinhardt-contrib/auth-jwt"]

[dependencies]
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
reinhardt-urls = { workspace = true, features = ["routers"] }
reinhardt-contrib = { workspace = true, features = ["auth"] }
reinhardt-pagination = { path = "../pagination" }
reinhardt-openapi = { path = "../openapi" }

[dev-dependencies]
reinhardt-rest = { workspace = true }
