[package]
publish = false
name = "reinhardt-rest-core"
version.workspace = true
description = "Core REST API functionality and base classes for Reinhardt"
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
jwt = ["dep:reinhardt-auth", "reinhardt-auth/jwt"]

[dependencies]
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
reinhardt-urls = { workspace = true, features = ["routers"] }
reinhardt-core = { workspace = true, features = ["auth"] }
reinhardt-pagination = { path = "../../../reinhardt-core/crates/pagination" }
reinhardt-auth = { workspace = true, optional = true }
reinhardt-openapi = { workspace = true }

[dev-dependencies]
reinhardt-rest = { workspace = true }
