[package]
name = "reinhardt-server"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "HTTP server implementation for Reinhardt framework"

[dependencies]
# Internal crates (optional)
reinhardt-server-core = { workspace = true, optional = true }

[features]
default = ["server"]
server = ["dep:reinhardt-server-core"]
graphql = ["server", "reinhardt-server-core/graphql"]
websocket = ["server", "reinhardt-server-core/websocket"]
server-full = [
  "server",
  "graphql",
  "websocket",
  "reinhardt-server-core/full",
]
