[package]
name = "reinhardt-types"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
reinhardt-http = { workspace = true }
reinhardt-exception = { workspace = true }
async-trait = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
bytes = { workspace = true }
hyper = { workspace = true }
