[package]
name = "reinhardt-types"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
reinhardt-http = { version = "0.1.0", path = "../../../reinhardt-http" }
reinhardt-exception = { version = "0.1.0", path = "../exception" }
async-trait = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
bytes = { workspace = true }
hyper = { workspace = true }
