[package]
name = "reinhardt-types"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Core type definitions and common types for the Reinhardt framework"
repository.workspace = true

[dependencies]
reinhardt-http = { workspace = true }
reinhardt-exception = { path = "../../../reinhardt-core/crates/exception" }
async-trait = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
bytes = { workspace = true }
hyper = { workspace = true }
