[package]
name = "reinhardt-types"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Core type definitions and common types for the Reinhardt framework"
repository.workspace = true

[dependencies]
reinhardt-http = { path = "../http", version = "0.1.0-alpha.1", optional = true }
reinhardt-exception = { path = "../exception", version = "0.1.0-alpha.1" }
async-trait = { workspace = true }

[features]
default = []
http = ["dep:reinhardt-http"]

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
bytes = { workspace = true }
hyper = { workspace = true }
