[package]
publish = false
name = "reinhardt-validators"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Data validation utilities with built-in validators for common use cases"
repository.workspace = true

[features]
full = []

[dependencies]
chrono = { workspace = true }
image = "0.25"
regex = "1.11"
serde_json = "1.0"
thiserror = "2.0"

[dev-dependencies]
tokio = { workspace = true }
