[package]
publish = false
name = "reinhardt-backends"
version.workspace = true
description = "Database backend implementations (PostgreSQL, MySQL, SQLite)"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tokio = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
sqlx = { workspace = true, features = ["chrono", "runtime-tokio", "uuid"] }
sea-query = { workspace = true, features = [
  "backend-postgres",
  "backend-mysql",
  "backend-sqlite",
  "sqlx-utils",
  "with-uuid",
] }
pg_escape = "0.1.1"
futures = { workspace = true }
rust_decimal = { workspace = true }
uuid = { workspace = true }
reinhardt-di = { workspace = true, optional = true }
reinhardt-conf = { workspace = true, optional = true }
[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "time"] }
serial_test = { workspace = true }
rstest = { workspace = true }
testcontainers = { workspace = true }
testcontainers-modules = { workspace = true }
reinhardt-test = { workspace = true, features = ["testcontainers"] }
uuid = { workspace = true }

[features]
default = ["postgres"]
postgres = ["sqlx/postgres"]
mysql = ["sqlx/mysql"]
sqlite = ["sqlx/sqlite"]
cockroachdb-backend = ["postgres"]
di = ["reinhardt-di"]
settings = ["dep:reinhardt-conf"]
all-databases = ["postgres", "mysql", "sqlite", "cockroachdb-backend"]
full = ["all-databases", "di", "settings"]
