[package]
publish = false
name = "reinhardt-metadata"
version = "0.1.0-alpha.1"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Metadata API for OPTIONS requests in Reinhardt framework"
repository.workspace = true

[features]
full = []

[dependencies]
reinhardt-core = { workspace = true, features = ["exception"] }
async-trait = "0.1"
regex = "1.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
reinhardt-rest = {workspace = true, features = ["serializers"]}

[dev-dependencies]
reinhardt-core = { workspace = true, features = ["exception"] }
tokio = { version = "1", features = ["full"] }
bytes = "1.9"
hyper = "1.5"
rstest = { workspace = true }
