[package]
name = "reinhardt-admin-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Core logic for Reinhardt admin panel"
keywords = ["reinhardt", "admin", "core", "web", "framework"]
categories = ["web-programming"]

[features]
default = []
# File upload handling
file-uploads = ["reinhardt-utils"]
# Admin panel features
admin = []
# All features
full = ["file-uploads"]

[dependencies]
# Shared type definitions

# Reinhardt dependencies
reinhardt-auth = { workspace = true }
reinhardt-core = { workspace = true }
reinhardt-db = { workspace = true, features = ["orm"] }
reinhardt-di = { workspace = true }
reinhardt-urls = { workspace = true, features = ["routers"] }
reinhardt-utils = { workspace = true, optional = true, features = ["storage"] }

# Core dependencies
tokio = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
parking_lot = { workspace = true }
dashmap = "6.1.0"
chrono = { workspace = true }
sea-query = { workspace = true }
rayon = "1.10"
csv = "1.3"
uuid = { workspace = true }
base64 = { workspace = true }
inventory = { workspace = true }
reinhardt-admin = {workspace = true, features = ["types"]}

[dev-dependencies]
reinhardt-db = { workspace = true }
tokio-test = { workspace = true }
rstest = { workspace = true }
reinhardt-test = { workspace = true, features = ["testcontainers", "admin"] }
