[package]
name = "reinhardt-openapi"
version = "0.1.0-alpha.16"
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "OpenAPI router wrapper for Reinhardt framework"

[dependencies]
reinhardt-urls = { workspace = true, features = ["routers"] }
reinhardt-rest = { workspace = true, features = ["openapi"] }
reinhardt-http = { workspace = true }
async-trait = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["full", "test-util"] }
hyper = { workspace = true }
rstest = { workspace = true }
