[package]
name = "serializers-ext"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
reinhardt-serializers = { workspace = true }
reinhardt-orm = { workspace = true }
reinhardt-apps = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
