# Base settings
debug = false
secret_key = "CHANGE_THIS_IN_PRODUCTION"
language_code = "en-us"
time_zone = "UTC"

[database]
engine = "postgresql"
host = "localhost"
port = 5432
name = "examples_database_integration_db"
user = "postgres"
password = "CHANGE_THIS"
