[package]
publish = false
name = "reinhardt-proxy"
version.workspace = true
description = "HTTP proxy and reverse proxy utilities"
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
reinhardt-db = { workspace = true, features = ["orm"] }

async-trait = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
futures = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
