[package]
name = "reinhardt-proxy"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
reinhardt-apps = { workspace = true }
reinhardt-orm = { workspace = true }

async-trait = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
futures = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
