[package]
name = "reinhardt-routers"
version.workspace = true
description = "URL routing and pattern matching"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
reinhardt-apps = { workspace = true }
reinhardt-viewsets = { path = "../../../reinhardt-views/crates/viewsets" }
reinhardt-routers-macros = { path = "../routers-macros", version = "0.1.0-alpha.1" }
reinhardt-di = { workspace = true, optional = true }
reinhardt-middleware = { workspace = true, optional = true }
reinhardt-exception = { path = "../../../reinhardt-core/crates/exception" }
regex = { workspace = true }
nom = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
hyper = { workspace = true }
chrono = { workspace = true }
once_cell = "1.20"
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = "0.9"
matchit = "0.9.0"
aho-corasick = "1.1"

[features]
default = ["unified-router"]
unified-router = ["reinhardt-di", "reinhardt-middleware"]

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
bytes = { workspace = true }
hyper = { workspace = true }
