[package]
name = "reinhardt-routers"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
reinhardt-apps = { workspace = true }
reinhardt-exception = { workspace = true }
reinhardt-viewsets = { workspace = true }
reinhardt-routers-macros = { path = "../routers-macros", version = "0.1.0" }
reinhardt-di = { workspace = true, optional = true }
reinhardt-middleware = { workspace = true, optional = true }
regex = { workspace = true }
nom = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
hyper = { workspace = true }
chrono = { workspace = true }
once_cell = "1.20"
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = "0.9"

[features]
default = ["unified-router"]
unified-router = ["reinhardt-di", "reinhardt-middleware"]

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
bytes = { workspace = true }
hyper = { workspace = true }
