[package]
publish = false
name = "reinhardt-routers"
version.workspace = true
description = "URL routing and pattern matching"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
reinhardt-views = { workspace = true, features = ["viewsets"] }
reinhardt-viewsets = { workspace = true }
reinhardt-routers-macros = { path = "../routers-macros", version = "0.1.0-alpha.1" }
reinhardt-middleware = { workspace = true, optional = true }
reinhardt-core = { workspace = true, features = ["exception", "types", "di"] }
reinhardt-db = { workspace = true, optional = true }
regex = { workspace = true }
nom = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
hyper = { workspace = true }
chrono = { workspace = true }
once_cell = "1.20"
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = "0.9"
matchit = "0.9.0"
aho-corasick = "1.1"
inventory = "0.3"

[features]
default = ["unified-router"]
unified-router = ["reinhardt-middleware"]
database = ["dep:reinhardt-db"]
full = ["unified-router", "database"]

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
bytes = { workspace = true }
hyper = { workspace = true }
