[package]
name = "reinhardt-viewsets"
version.workspace = true
description = "ViewSet implementations for DRY CRUD operations"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
reinhardt-apps = { workspace = true }
reinhardt-di = { workspace = true }
reinhardt-db = { workspace = true, features = ["orm"] }
reinhardt-auth = { path = "../../../reinhardt-contrib/crates/auth" }
reinhardt-cache = { path = "../../../reinhardt-utils/crates/cache" }
reinhardt-serializers = { path = "../../../reinhardt-rest/crates/serializers" }
reinhardt-filters = { path = "../../../reinhardt-rest/crates/filters" }
reinhardt-pagination = { path = "../../../reinhardt-rest/crates/pagination" }
reinhardt-macros = { path = "../../../reinhardt-core/crates/macros" }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
hyper = { workspace = true }
uuid = { workspace = true }
sqlx = { workspace = true, features = [
  "any",
  "sqlite",
  "runtime-tokio",
  "tls-rustls",
] }
inventory = "0.3"
lazy_static = "1.4"
urlencoding = "2.1"

[dev-dependencies]
tokio = { workspace = true }
tokio-test = "0.4"
bytes = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
