[package]
publish = false
name = "reinhardt-viewsets"
version.workspace = true
description = "ViewSet implementations for DRY CRUD operations"
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
argon2-hasher = ["reinhardt-auth/argon2-hasher"]

[dependencies]
reinhardt-db = { workspace = true, features = ["orm"] }
reinhardt-core = { workspace = true, features = [
  "exception",
  "types",
  "macros",
  "http",
  "pagination",
] }
reinhardt-pagination = { workspace = true }
reinhardt-auth = { workspace = true }
reinhardt-utils = { workspace = true, features = ["cache"] }
reinhardt-serializers = { path = "../../../reinhardt-rest/crates/serializers", version = "0.1.0-alpha.1" }
reinhardt-filters = { path = "../../../reinhardt-rest/crates/filters", version = "0.1.0-alpha.1" }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
hyper = { workspace = true }
uuid = { workspace = true }
sqlx = { workspace = true, features = [
  "any",
  "sqlite",
  "runtime-tokio",
  "tls-rustls",
] }
inventory = "0.3"
lazy_static = "1.4"
urlencoding = "2.1"

[dev-dependencies]
tokio = { workspace = true }
tokio-test = "0.4"
bytes = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
