[package]
name = "reinhardt-viewsets"
version.workspace = true
description = "ViewSet implementations for DRY CRUD operations"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
reinhardt-apps = { workspace = true }
reinhardt-di = { workspace = true }
reinhardt-orm = { workspace = true }
reinhardt-serializers = { workspace = true }
reinhardt-macros = { workspace = true }
reinhardt-auth = { workspace = true }
reinhardt-filters = { workspace = true }
reinhardt-pagination = { workspace = true }
reinhardt-cache = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
hyper = { workspace = true }
uuid = { workspace = true }
sqlx = { workspace = true, features = [
  "any",
  "sqlite",
  "runtime-tokio",
  "tls-rustls",
] }
inventory = "0.3"
lazy_static = "1.4"
urlencoding = "2.1"

[dev-dependencies]
tokio = { workspace = true }
tokio-test = "0.4"
bytes = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
