[package]
publish = false
name = "reinhardt-associations"
version.workspace = true
description = "Database relationship and association management"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
reinhardt-core = { workspace = true }
sea-query = { workspace = true }
reinhardt-db = {workspace = true, features = ["orm"]}

[dev-dependencies]
reinhardt-test = { workspace = true, features = ["testcontainers"] }
rstest = { workspace = true }
serial_test = { workspace = true }
sqlx = { workspace = true, features = ["runtime-tokio", "postgres"] }
tokio = { workspace = true }
testcontainers = { workspace = true }

[features]
full = []
