[package]
publish = false
name = "reinhardt-exception"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Unified error types and result handling for the Reinhardt framework"
repository.workspace = true

[dependencies]
thiserror = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
http = { workspace = true }
validator = "0.20"
