[package]
name = "reinhardt-views-core"
version.workspace = true
description = "Core view functionality and base classes"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
reinhardt-db = { workspace = true, features = ["orm"] }
reinhardt-core = { workspace = true, features = ["serializers", "exception", "apps"] }
async-trait = { workspace = true }
bytes = { workspace = true }
hyper = { workspace = true }
http-body-util = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tera = { workspace = true }
syntect = { workspace = true }
once_cell = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
