[package]
name = "reinhardt-views-core"
version.workspace = true
description = "Core view functionality and base classes"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
reinhardt-apps = { workspace = true }
reinhardt-db = { workspace = true, features = ["orm"] }
reinhardt-serializers = { path = "../../../reinhardt-rest/crates/serializers" }
reinhardt-exception = { path = "../../../reinhardt-core/crates/exception" }
async-trait = { workspace = true }
bytes = { workspace = true }
hyper = { workspace = true }
http-body-util = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tera = { workspace = true }
syntect = { workspace = true }
once_cell = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
