[package]
name = "reinhardt-seeding-macros"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Procedural macros for reinhardt-seeding crate"
repository.workspace = true
authors.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true }
quote = { workspace = true }
proc-macro2 = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
