[package]
publish = false
name = "reinhardt-macros"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Procedural macros for Reinhardt framework"
repository.workspace = true
authors.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"
proc-macro-crate = "3.1"
nom = "8"
ctor = "0.6.0"
inventory = "0.3"

[features]
full = []
db-postgres = []
db-mysql = []
db-sqlite = []

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "time"] }
trybuild = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reinhardt-db = { workspace = true, features = ["orm", "migrations"] }
reinhardt-migrations = { workspace = true }
reinhardt-orm = { workspace = true }
reinhardt-signals = { workspace = true }
serial_test = { workspace = true }
reinhardt-di = { workspace = true }
reinhardt-http = { workspace = true }
async-trait = { workspace = true }
reinhardt-apps = { workspace = true }
reinhardt = { workspace = true, features = ["database"] }
reinhardt-associations = { workspace = true }
chrono = { workspace = true }
linkme = { workspace = true }
reinhardt-admin-core = { workspace = true }
