[package]
name = "reinhardt-admin-types"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Shared type definitions for Reinhardt admin panel"
keywords = ["reinhardt", "admin", "types", "api", "web"]
categories = ["web-programming"]

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_bytes = { workspace = true }
thiserror = { workspace = true }
reinhardt-core = {workspace = true, features = ["exception"]}
