[package]
publish = false
name = "reinhardt-browsable-api"
version.workspace = true
description = "HTML interface for browsing and interacting with REST APIs"
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
full = []

[dependencies]
reinhardt-core = { workspace = true, features = ["exception", "types"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tera = { workspace = true }
thiserror = "2.0"
anyhow = { workspace = true }
async-trait = { workspace = true }
hyper = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
hyper = { workspace = true }
bytes = { workspace = true }
rstest = { workspace = true }
testcontainers = { workspace = true }
sqlx = { workspace = true }
tempfile = { workspace = true }
reinhardt-test = { workspace = true, features = ["testcontainers"] }
