[package]
name = "reinhardt-browsable-api"
version.workspace = true
description = "HTML interface for browsing and interacting with REST APIs"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tera = { workspace = true }
thiserror = "2.0"
anyhow = { workspace = true }
async-trait = { workspace = true }
hyper = { workspace = true }
reinhardt-apps = { version = "0.1.0", path = "../../../reinhardt-apps" }

[dev-dependencies]
tokio = { workspace = true }
hyper = { workspace = true }
bytes = { workspace = true }
