[package]
name = "reinhardt-di-core"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "FastAPI-style dependency injection system for Reinhardt"
repository.workspace = true

[dependencies]
thiserror = { workspace = true }
async-trait = { workspace = true }
reinhardt-apps = { workspace = true }
reinhardt-params = { path = "../../../reinhardt-di/crates/params" }

[dev-dependencies]
reinhardt-di = { workspace = true }
tokio-test = { workspace = true }
