[package]
name = "reinhardt-auth"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
default = []
database = ["sqlx", "sea-query", "sea-query-binder"]
redis-sessions = ["redis"]

[dependencies]
reinhardt-types = { workspace = true }
reinhardt-http = { workspace = true }
reinhardt-exception = { workspace = true }
reinhardt-apps = { workspace = true }
reinhardt-di = { workspace = true }
reinhardt-orm = { workspace = true }
argon2 = { workspace = true }
rand = { workspace = true }
jsonwebtoken = { workspace = true }
clap = { version = "4.5", features = ["derive"] }
console = "0.15"
dialoguer = "0.11"
uuid = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
base64 = "0.22"
sha2 = { workspace = true }
reqwest = { version = "0.12", features = ["json"] }
sqlx = { workspace = true, optional = true }
sea-query = { version = "1.0.0-rc.1", features = [
  "backend-postgres",
  "backend-mysql",
  "backend-sqlite",
], optional = true }
sea-query-binder = { version = "0.7", features = [
  "sqlx-postgres",
  "sqlx-mysql",
  "sqlx-sqlite",
], optional = true }
redis = { workspace = true, optional = true }

[dev-dependencies]
tokio = { workspace = true }
hyper = { workspace = true }
bytes = { workspace = true }
