[package]
name = "examples-twitter"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "manage"
path = "src/bin/manage.rs"

[dependencies]
reinhardt = { path = "../../..", package = "reinhardt-web", features = [
	"full",
] }
clap = { version = "4", features = ["derive"] }
console = "0.16.1"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.11", features = ["v4", "serde"] }
ctor = "0.6.3"
validator = { version = "0.20.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
rstest = "0.26.1"
reqwest = { version = "0.12", features = ["json"] }
