[package]
publish = false
name = "reinhardt-backends-pool"
version.workspace = true
description = "Database connection pooling for various backends"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
thiserror = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
sqlx = { workspace = true }

[dev-dependencies]
reinhardt-db = { workspace = true, features = ["backends", "pool", "postgres"] }

[features]
default = []
