[package]
name = "reinhardt-http"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "HTTP primitives, request and response handling for Reinhardt"
repository.workspace = true

[dependencies]
bytes = { workspace = true }
hyper = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
futures = "0.3.31"
thiserror = { workspace = true }
reinhardt-parsers = { path = "../parsers", optional = true }
reinhardt-exception = { path = "../exception" }
async-trait = "0.1"
tokio = { version = "1.0", features = ["sync"] }
percent-encoding = "2.3"

[features]
default = []
parsers = ["dep:reinhardt-parsers"]
