[package]
publish = false
name = "reinhardt-utils-core"
version.workspace = true
description = "Core utility functions and helpers"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
chrono = { workspace = true }
chrono-tz = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
